version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    depends_on:
      - backend
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
